List<String> worldLanguages = [
  "Mandarin Chinese",
  "Spanish",
  "English",
  "Hindi",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Western Punjabi",
  "Marathi",
  "Telugu",
  "Wu Chinese",
  "Turkish",
  "Korean",
  "French",
  "German",
  "Vietnamese",
  "Tamil",
  "Yue Chinese (Cantonese)",
  "Urdu",
  "Javanese",
  "Italian",
  "Egyptian Arabic",
  "Gujarati",
  "Iranian Persian (Farsi)",
  "Bhojpuri",
  "Southern Min (Hokkien-Taiwanese)",
  "Hausa",
  "Thai",
  "Kannada",
  "Burmese",
  "Polish",
  "Amharic",
  "Odia",
  "Malayalam",
  "Sundanese",
  "Hausa",
  "Swahili",
  "Romanian",
  "Cebuano",
  "Dutch",
  "Hungarian",
  "Greek",
  "Czech",
  "Swedish",
  "Belarusian",
  "Serbo-Croatian",
  "Tagalog",
  "Ukrainian",
  "Azerbaijani",
  "Burmese",
  "Hebrew",
  "Finnish",
  "Slovak",
  "Norwegian",
  "Danish",
  "Croatian",
  "Slovenian",
  "Bulgarian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Albanian",
  "Macedonian",
  "Georgian",
  "Armenian",
  "Mongolian",
  "Khmer",
  "Lao",
  "Nepali",
  "Sinhala",
  "Pashto",
  "Somali",
  "Tajik",
  "Uzbek",
  "Turkmen",
  "Kyrgyz",
  "Kazakh",
  "Bosnian",
  "Icelandic",
  "Maltese",
  "Luxembourgish",
  "Galician",
  "Welsh",
  "Irish",
  "Scottish Gaelic",
  "Basque",
  "Catalan",
  "Corsican",
  "Breton",
  "Maori",
  "Haitian Creole",
  "Zulu",
  "Xhosa",
  "Afrikaans",
  "Yoruba",
  "Igbo",
  "Shona",
  "Sesotho",
  "Tswana",
  "Tsonga",
  "Kurdish",
  "Quechua",
  "Aymara",
  "Guarani",
  "Navajo",
  "Hmong",
  "Fijian",
  "Samoan",
  "Tongan",
  "Tahitian",
  "Marshallese",
  "Chuukese",
  "Pohnpeian",
  "Kiribati",
  "Twi",
  "Wolof",
  "Mandinka",
  "Fula",
  "Bambara",
  "Songhay",
  "Berber",
  "Tamazight",
  "Malagasy",
  "Amis",
  "Aboriginal Australian Languages",
  "Inuit",
  "Greenlandic",
  "Tatar",
  "Uyghur",
  "Tibetan",
  "Rohingya",
  "Balochi",
  "Sylheti",
  "Chittagonian",
  "Magahi",
  "Maithili",
  "Santali",
  "Marwari",
  "Rajasthani",
  "Sindhi",
  "Saraiki",
  "Konkani",
  "Kashmiri",
  "Dogri",
  "Meitei (Manipuri)",
  "Assamese",
  "Nepal Bhasa (Newari)",
  "Bhutanese (Dzongkha)",
  "Chakma",
  "Sanskrit",
];

List<bool> worldLanguagesStatus = List.filled(worldLanguages.length, false);