/// job Skills
List jobSkills = [
// Technical Skills
  "Programming",
  "Data Analysis",
  "Project Management",
  "Web Development",
  "Database Management",
  "Software Development",
  "Machine Learning",
  "Cybersecurity",
  "Cloud Computing",
  "Network Administration",
  "Technical Writing",
  "Quality Assurance",
  "Graphic Design",
  "SEO",
  "UX/UI Design",
  "Digital Marketing",
  "Product Management",
  "Blockchain",
  "AI Development",
  "Business Analysis",
  "Mobile App Development",
  "DevOps",
  "IT Support",
  "Systems Architecture",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Construction Management",
  "Biotechnology",
  "Chemical Analysis",

// Soft Skills
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Time Management",
  "Adaptability",
  "Critical Thinking",
  "Leadership",
  "Creativity",
  "Emotional Intelligence",
  "Negotiation",
  "Conflict Resolution",
  "Decision Making",
  "Attention to Detail",
  "Interpersonal Skills",
  "Self-Motivation",
  "Public Speaking",
  "Customer Service",
  "Networking",
  "Presentation Skills",
  "Writing Skills",
  "Cultural Competence",
  "Stress Management",
  "Organization",
  "Active Listening",
  "Empathy",
  "Strategic Thinking",
  "Influence",

// Business and Finance Skills
  "Financial Analysis",
  "Accounting",
  "Budget Management",
  "Sales",
  "Market Research",
  "Business Development",
  "Supply Chain Management",
  "Logistics",
  "Human Resources",
  "Talent Acquisition",
  "Risk Management",
  "Operational Management",
  "Negotiation",

// Other Skills
  "Foreign Language Proficiency",
  "Teaching and Training",
  "Research Skills",
  "Technical Support",
  "Health and Safety Management",
  "First Aid",
  "Project Coordination",
  "Event Planning",
  "Legal Knowledge",
  "Copyrighting",
  "Editing",
  "Photography",
  "Video Production",
  "Social Media Management",
  "Content Creation",
  "Culinary Skills",
  "Customer Relationship Management",
  "Data Entry",
  "Statistical Analysis",
  "Laboratory Skills",
  "Manual Dexterity",
  "Operating Heavy Machinery",
  "Driving",
  "Public Relations",
];
List<bool> jobSkillsStatus = List.filled(jobSkills.length, false);
